/**
 * Scoped real-pointer audit for the opt-in diamond/role-label trial.
 * node tools/check_hypergraph_diamond_trial.mjs HTML BUNDLE OUTPUT [smoke|full]
 * An isolated local Chrome context is used; no personal browser state is read.
 */
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),{chromium}=require(process.env.HK_PLAYWRIGHT_MODULE||'playwright');
const [htmlArg,bundleArg,outArg,mode='full']=process.argv.slice(2);
if(!htmlArg||!bundleArg||!outArg)throw new Error('Expected HTML BUNDLE OUTPUT [smoke|full]');
const html=resolve(htmlArg),bundle=resolve(bundleArg),output=resolve(outArg),pause=Number(process.env.HK_QA_SETTLE_MS||230);
await mkdir(output,{recursive:true});
const readRows=async name=>(await readFile(join(bundle,name),'utf8')).split(/\r?\n/).filter(Boolean).map(JSON.parse);
const [nodes,edges,members]=await Promise.all(['nodes.jsonl','assertions.jsonl','members.jsonl'].map(readRows));
const uniq=xs=>[...new Set(xs.map(String))].sort(),same=(a,b)=>JSON.stringify(uniq(a))===JSON.stringify(uniq(b)),attr=JSON.stringify;
const nodeIds=nodes.map(n=>n.id),edgeIds=edges.map(e=>e.id),memberIds=id=>uniq(members.filter(m=>m.assertion_id===id).map(m=>m.node_id));
const incident=id=>uniq(members.filter(m=>m.node_id===id).map(m=>m.assertion_id)),pairs=uniq(members.map(m=>`${m.assertion_id}|${m.node_id}`));
const sourceRoles=(e,n)=>uniq(members.filter(m=>m.assertion_id===e&&m.node_id===n).map(m=>m.role));
const sha=async path=>createHash('sha256').update(await readFile(path)).digest('hex');
const report={html,bundle,mode,sha256:await sha(html),startedAt:new Date().toISOString(),checks:[],states:[],interactions:[],errors:[],blockedNetwork:[],screenshots:[]};
if(process.env.HK_QA_FROZEN_HTML)report.frozen={path:resolve(process.env.HK_QA_FROZEN_HTML),sha256:await sha(resolve(process.env.HK_QA_FROZEN_HTML))};
const check=(name,ok,detail={})=>report.checks.push({name,ok:Boolean(ok),detail});
const browser=await chromium.launch({headless:true,executablePath:process.env.HK_BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,locale:'zh-CN',colorScheme:'light'}),page=await context.newPage();
page.setDefaultTimeout(4500);page.on('pageerror',e=>report.errors.push({kind:'pageerror',message:e.stack}));page.on('console',m=>{if(m.type()==='error')report.errors.push({kind:'console',message:m.text()});});
await page.route(/^https?:/,route=>{report.blockedNetwork.push(route.request().url());return route.abort();});
const settle=()=>page.waitForTimeout(pause),park=async()=>{await page.mouse.move(1,1);await settle();};let imageIndex=0;
async function shot(name){const path=join(output,`${String(++imageIndex).padStart(3,'0')}-${name.replace(/[^a-z0-9_-]/gi,'-')}.png`);await page.screenshot({path,fullPage:false});report.screenshots.push(path);return path;}
async function task(name,fn){const start=report.checks.length;try{await fn();}catch(e){check(name,false,{error:e.stack});}const failed=report.checks.slice(start).filter(c=>!c.ok);if(failed.length){const screenshot=await shot(`FAIL-${name}`);failed.forEach(c=>c.screenshot=screenshot);}console.log(JSON.stringify({task:name,checks:report.checks.length-start,failed:failed.length}));}
async function pointer(locator,name,kind='click'){
 locator=locator.first();if(!await locator.count())throw new Error(`Missing target ${name}`);await locator.scrollIntoViewIfNeeded();await settle();
 const point=await locator.evaluate(e=>{const b=e.getBoundingClientRect(),visible=p=>p.x>=0&&p.y>=0&&p.x<innerWidth&&p.y<innerHeight,accept=p=>{if(!visible(p))return false;const hit=document.elementFromPoint(p.x,p.y);return hit===e||e.contains(hit)||(e.closest('.overview-edge')&&hit?.closest('.overview-edge')===e.closest('.overview-edge'));};
  if(e.classList.contains('overview-link')&&e.getTotalLength){const matrix=e.getScreenCTM(),length=e.getTotalLength();for(let i=0;i<160;i++){const p=e.getPointAtLength(length*(i+.5)/160),screen=new DOMPoint(p.x,p.y).matrixTransform(matrix);if(accept(screen))return{x:screen.x,y:screen.y};}}
  else{const center={x:b.x+b.width/2,y:b.y+b.height/2};if(accept(center))return center;for(let x=1;x<10;x++)for(let y=1;y<10;y++){const p={x:b.x+b.width*x/10,y:b.y+b.height*y/10};if(accept(p))return p;}}return null;});
 if(!point)throw new Error(`No exposed pointer target ${name}`);
 const hit=await page.evaluate(p=>{const e=document.elementFromPoint(p.x,p.y),owner=e?.closest('.overview-edge,.overview-node,.overview-link');return{tag:e?.tagName,class:e?.getAttribute('class'),node:owner?.dataset.node,assertion:owner?.dataset.assertion};},point);
 report.interactions.push({name,kind,point,hit});if(kind==='hover')await page.mouse.move(point.x,point.y);else await page.mouse.click(point.x,point.y);await settle();return point;
}
const contract={shape:'.overview-edge-label',name:'.overview-edge-text',code:'.overview-edge-code',role:'.overview-role-label'};
const edgeMark=id=>page.locator(`.overview-edge[data-assertion=${attr(id)}] ${contract.shape}`),nodeMark=id=>page.locator(`.overview-node[data-node=${attr(id)}] .node-halo`),linkMark=(e,n)=>page.locator(`.overview-link[data-assertion=${attr(e)}][data-node=${attr(n)}]`);
const clear=async()=>{await pointer(page.locator('.overview-clear'),'clear');await park();};
const view=async id=>{await pointer(page.locator(`[data-representation=${attr(id)}]`),`view:${id}`);await park();};
const setTheme=async name=>{if(await page.locator('html').getAttribute('data-theme')!==name)await pointer(page.locator('#theme-toggle'),`theme:${name}`);await park();};
async function readState(){return page.evaluate(c=>{
 const all=s=>[...document.querySelectorAll(s)],rect=e=>{if(!e)return null;const b=e.getBoundingClientRect();return{x:b.x,y:b.y,width:b.width,height:b.height,right:b.right,bottom:b.bottom};},bbox=e=>{if(!e)return null;const b=e.getBBox();return{x:b.x,y:b.y,width:b.width,height:b.height};};
 const flags=e=>({hidden:e.classList.contains('is-hidden')||getComputedStyle(e).display==='none'||getComputedStyle(e).visibility==='hidden',related:e.classList.contains('is-overview-related'),muted:e.classList.contains('is-overview-muted'),selected:e.classList.contains('is-selected'),opacity:Number(getComputedStyle(e).opacity)});
 const nodes=all('.overview-node').map(e=>({id:e.dataset.node,degree:Number(e.dataset.hyperedgeDegree),transform:e.getAttribute('transform'),box:rect(e.querySelector('.node-halo')),textBox:rect(e.querySelector('.node-inside-label')),...flags(e)}));
 const edges=all('.overview-edge').map(e=>{const shape=e.querySelector(c.shape),name=e.querySelector(c.name),code=e.querySelector(c.code),shapeBox=bbox(shape),segments=[...(name?.querySelectorAll('tspan')||[])];return{id:e.dataset.assertion,transform:e.getAttribute('transform'),shapeTag:shape?.tagName,shapePath:shape?.getAttribute('d'),shapeBox,shapeScreen:rect(shape),name:name?.textContent,nameBox:bbox(name),nameScreen:rect(name),textSegments:(segments.length?segments:name?[name]:[]).map(t=>({text:t.textContent,box:bbox(t)})),code:code?.textContent,codeBox:bbox(code),codeScreen:rect(code),...flags(e)};});
 const links=all('.overview-link').map(e=>({assertion:e.dataset.assertion,node:e.dataset.node,d:e.getAttribute('d'),...flags(e)}));
 const roles=all(c.role).map(e=>({assertion:e.dataset.assertion,node:e.dataset.node,value:e.dataset.role,text:e.textContent,transform:e.getAttribute('transform'),box:rect(e),rect:bbox(e.querySelector('rect')),textBox:bbox(e.querySelector('text')),display:getComputedStyle(e).display,visibility:getComputedStyle(e).visibility,opacity:Number(getComputedStyle(e).opacity),class:e.getAttribute('class')}));
 return{nodes,edges,links,roles,view:document.querySelector('.representation-button[aria-pressed=true]')?.dataset.representation,theme:document.documentElement.dataset.theme,viewport:document.querySelector('.hypergraph-overview .viewport')?.getAttribute('transform'),viewBox:document.querySelector('.hypergraph-overview .network-svg')?.getAttribute('viewBox'),drawer:all('#drawer-body .detail-grid dd').map(e=>e.textContent.trim()),tooltip:document.querySelector('.hypergraph-overview .tooltip.visible')?.textContent||null,tooltipBox:rect(document.querySelector('.hypergraph-overview .tooltip.visible')),readerEdge:document.querySelector('.single-edge-reader')?.dataset.currentAssertion,readerNodes:all('.single-edge-reader .entity-mark').map(e=>e.dataset.node),overflow:document.documentElement.scrollWidth>innerWidth,width:innerWidth,height:innerHeight,scroll:{x:scrollX,y:scrollY}};
 },contract);}
const geometry=s=>JSON.stringify({nodes:s.nodes.map(n=>[n.id,n.transform]),edges:s.edges.map(e=>[e.id,e.transform,e.shapePath]),links:s.links.map(l=>[l.assertion,l.node,l.d]),viewport:s.viewport,viewBox:s.viewBox});
const roleVisible=r=>r.display!=='none'&&r.visibility!=='hidden'&&r.opacity>.05;
function auditText(name,s){
 check(`${name}:all original edge names`,s.edges.every(e=>e.name?.replace(/\s/g,'')===edges.find(a=>a.id===e.id)?.predicate?.replace(/\s/g,'')),s.edges.map(e=>({id:e.id,text:e.name})));
 check(`${name}:18 unique E numbers`,s.edges.length===18&&s.edges.every(e=>/^E\s*\d+$/.test(e.code||''))&&same(s.edges.map(e=>Number(e.code?.replace(/^E\s*/,''))),Array.from({length:18},(_,i)=>i+1)),s.edges.map(e=>({id:e.id,code:e.code})));
 check(`${name}:E numbers above diamonds`,s.edges.every(e=>e.codeBox&&e.shapeBox&&e.codeBox.y+e.codeBox.height<=e.shapeBox.y+1),s.edges.map(e=>({id:e.id,codeBox:e.codeBox,shapeBox:e.shapeBox})));
 const outside=[];for(const e of s.edges){const b=e.shapeBox;if(!b){outside.push({id:e.id,error:'no diamond'});continue;}const cx=b.x+b.width/2,cy=b.y+b.height/2,rx=b.width/2,ry=b.height/2;for(const segment of e.textSegments){const t=segment.box;for(const [x,y] of [[t.x,t.y],[t.x+t.width,t.y],[t.x,t.y+t.height],[t.x+t.width,t.y+t.height]])if(Math.abs(x-cx)/rx+Math.abs(y-cy)/ry>1.015)outside.push({id:e.id,text:segment.text,point:{x,y},diamond:b});}}
 check(`${name}:real text bounds inside diamond`,outside.length===0,outside);
 check(`${name}:large filled diamonds`,s.edges.every(e=>e.shapeTag?.toLowerCase()==='path'&&e.shapeBox?.width>60&&e.shapeBox?.height>40),s.edges.map(e=>({id:e.id,shapeBox:e.shapeBox})));
 const labels=[...s.edges.flatMap(e=>[{id:`${e.id}:name`,box:e.nameScreen},{id:`${e.id}:code`,box:e.codeScreen}]),...s.nodes.map(n=>({id:n.id,box:n.textBox}))].filter(l=>l.box),collisions=[];
 for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i].box,b=labels[j].box,w=Math.min(a.right,b.right)-Math.max(a.x,b.x),h=Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y);if(w>1&&h>1)collisions.push({a:labels[i].id,b:labels[j].id,width:w,height:h});}
 check(`${name}:no text-label overlap`,collisions.length===0,collisions);
}
async function inspect(name,{focus=null,selected=null,baseline=null,text=false}={}){
 const s=await readState();s.name=name;report.states.push(s);check(`${name}:overview retained`,s.view==='overview');check(`${name}:39 canonical nodes`,s.nodes.length===39&&same(s.nodes.map(n=>n.id),nodeIds));check(`${name}:18 source hyperedges`,s.edges.length===18&&same(s.edges.map(e=>e.id),edgeIds));check(`${name}:65 membership pairs`,s.links.length===65&&same(s.links.map(l=>`${l.assertion}|${l.node}`),pairs));check(`${name}:nothing hidden`,[...s.nodes,...s.edges,...s.links].every(e=>!e.hidden));check(`${name}:global degrees`,s.nodes.every(n=>n.degree===incident(n.id).length));
 if(baseline)check(`${name}:fixed SVG geometry`,geometry(s)===geometry(baseline));
 const activeEdges=focus?(focus.kind==='node'?incident(focus.id):[focus.id]):[],activeNodes=focus?uniq([...(focus.kind==='node'?[focus.id]:[]),...activeEdges.flatMap(memberIds)]):[];
 check(`${name}:focused edges`,same(s.edges.filter(e=>e.related).map(e=>e.id),activeEdges));check(`${name}:focused nodes`,same(s.nodes.filter(e=>e.related).map(e=>e.id),activeNodes));
 const expectedRolePairs=focus?(focus.kind==='node'?pairs.filter(p=>p.endsWith(`|${focus.id}`)):pairs.filter(p=>p.startsWith(`${focus.id}|`))):[],activeRoles=s.roles.filter(roleVisible);
 check(`${name}:exact visible role memberships`,activeRoles.length===expectedRolePairs.length&&same(activeRoles.map(r=>`${r.assertion}|${r.node}`),expectedRolePairs),{actual:activeRoles.map(r=>`${r.assertion}|${r.node}`),expected:expectedRolePairs});
 check(`${name}:all role source text retained`,activeRoles.every(r=>same((r.value||'').split(' / '),sourceRoles(r.assertion,r.node))&&r.text.replace(/\s/g,'')===(r.value||'').replace(/\s/g,'')),activeRoles.map(r=>({assertion:r.assertion,node:r.node,value:r.value,text:r.text})));
 check(`${name}:role text fits its label`,activeRoles.every(r=>r.rect&&r.textBox&&r.textBox.x>=r.rect.x-1&&r.textBox.y>=r.rect.y-1&&r.textBox.x+r.textBox.width<=r.rect.x+r.rect.width+1&&r.textBox.y+r.textBox.height<=r.rect.y+r.rect.height+1),activeRoles.map(r=>({assertion:r.assertion,node:r.node,rect:r.rect,textBox:r.textBox})));
 const worldScale=s.edges[0]?.shapeScreen?.width/s.edges[0]?.shapeBox?.width,clearances=[];for(const r of activeRoles)for(const n of s.nodes){const b=r.box,c=n.box,cx=c.x+c.width/2,cy=c.y+c.height/2,x=Math.max(b.x,Math.min(cx,b.right)),y=Math.max(b.y,Math.min(cy,b.bottom)),gap=Math.hypot(cx-x,cy-y)-c.width/2;clearances.push({role:`${r.assertion}|${r.node}`,node:n.id,gapPx:gap,gapWorld:gap/worldScale});}
 s.roleNodeMinimumClearance=clearances.length?clearances.reduce((a,b)=>a.gapWorld<b.gapWorld?a:b):null;check(`${name}:role-node safe clearance`,clearances.every(c=>c.gapWorld>=11.5),clearances.filter(c=>c.gapWorld<11.5));
 const overlap=(a,b)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)),roleCollisions=[];for(let i=0;i<activeRoles.length;i++)for(let j=i+1;j<activeRoles.length;j++){const area=overlap(activeRoles[i].box,activeRoles[j].box);if(area>.2)roleCollisions.push({a:`${activeRoles[i].assertion}|${activeRoles[i].node}`,b:`${activeRoles[j].assertion}|${activeRoles[j].node}`,area});}check(`${name}:role labels do not overlap`,roleCollisions.length===0,roleCollisions);
 s.tooltipRoleOverlaps=s.tooltipBox?activeRoles.filter(r=>overlap(r.box,s.tooltipBox)>.2).map(r=>({assertion:r.assertion,node:r.node,value:r.value,overlapArea:overlap(r.box,s.tooltipBox)})):[];
 if(selected)check(`${name}:selected record`,s.drawer.includes(selected.id),{selected,drawer:s.drawer});
 if(text)auditText(name,s);return s;
}
const largest=[...edges].sort((a,b)=>memberIds(b.id).length-memberIds(a.id).length)[0].id,highest=[...nodes].sort((a,b)=>incident(b.id).length-incident(a.id).length)[0].id;
try{
 if(process.env.HK_QA_EXPECTED_HASH&&report.sha256!==process.env.HK_QA_EXPECTED_HASH)throw new Error(`Export hash mismatch: ${report.sha256}`);
 if(process.env.HK_QA_FROZEN_HASH&&report.frozen?.sha256!==process.env.HK_QA_FROZEN_HASH)throw new Error(`Legacy frozen export hash mismatch: ${report.frozen?.sha256}`);
 await page.goto(pathToFileURL(html).href);await settle();
 await task('source-and-default',async()=>{check('source counts',nodes.length===39&&edges.length===18&&members.length===65);check('default light',await page.locator('html').getAttribute('data-theme')==='light');await inspect('default',{text:true});});
 for(const size of [{width:1920,height:1080},{width:1440,height:1000}])await task(`preview:${size.width}`,async()=>{await page.setViewportSize(size);await page.waitForTimeout(500);await view('overview');await clear();for(const theme of ['light','dark']){await setTheme(theme);const before=await inspect(`preview:${size.width}:${theme}`,{text:true});await shot(`diamond-${size.width}-${theme}`);await pointer(edgeMark(largest),`hover:${size.width}:${theme}:largest`,'hover');await inspect(`preview-hover:${size.width}:${theme}`,{focus:{kind:'assertion',id:largest},baseline:before,text:true});await shot(`diamond-${size.width}-${theme}-roles-hover`);await park();await inspect(`preview-cleared:${size.width}:${theme}`,{baseline:before});}});
 if(mode==='full'){
  await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(500);await view('overview');await setTheme('light');await clear();
  for(const e of edges)await task(`diamond:${e.id}`,async()=>{await clear();const before=await inspect(`before:${e.id}`),selected={kind:'assertion',id:e.id};await pointer(edgeMark(e.id),`diamond-hover:${e.id}`,'hover');await inspect(`diamond-hover:${e.id}`,{focus:selected,baseline:before,text:true});await pointer(edgeMark(e.id),`diamond-click:${e.id}`);await park();await inspect(`diamond-selected:${e.id}`,{focus:selected,selected,baseline:before,text:true});await clear();await pointer(page.locator(`.overview-edge[data-assertion=${attr(e.id)}] ${contract.code}`),`E-code-click:${e.id}`);await park();await inspect(`E-code-selected:${e.id}`,{focus:selected,selected,baseline:before,text:true});await pointer(page.locator('.overview-read'),`read:${e.id}`);const reader=await readState();check(`reader exact edge:${e.id}`,reader.view==='contour'&&reader.readerEdge===e.id&&same(reader.readerNodes,memberIds(e.id)));await pointer(page.locator('.overview-return'),`return:${e.id}`);await park();await inspect(`returned:${e.id}`,{focus:selected,selected,baseline:before});});
  for(const n of nodes)await task(`node:${n.id}`,async()=>{await clear();const before=await inspect(`before-node:${n.id}`),selected={kind:'node',id:n.id};await pointer(nodeMark(n.id),`node-hover:${n.id}`,'hover');await inspect(`node-hover:${n.id}`,{focus:selected,baseline:before});if(n.id===highest)await shot('hub-all-direct-roles-hover');await pointer(nodeMark(n.id),`node-click:${n.id}`);await park();const selectedState=await inspect(`node-selected:${n.id}`,{focus:selected,selected,baseline:before});if(['person:su-shi','person:su-zhe','place:west-lake','time:1089'].includes(n.id)){await shot(`selected-${n.id}-roles`);if(n.id==='person:su-shi')check('SuShi has exactly 18 direct role labels',selectedState.roles.filter(roleVisible).length===18);if(n.id==='person:su-zhe')check('SuZhe has exactly 4 direct role labels',selectedState.roles.filter(roleVisible).length===4);}});
  for(const pair of pairs)await task(`membership:${pair}`,async()=>{await clear();const [e,n]=pair.split('|'),before=await inspect(`before-membership:${pair}`),selected={kind:'assertion',id:e};await pointer(linkMark(e,n),`membership-hover:${pair}`,'hover');const hovered=await inspect(`membership-hover:${pair}`,{focus:selected,baseline:before});check(`tooltip roles:${pair}`,sourceRoles(e,n).every(role=>hovered.tooltip?.includes(role)),{tooltip:hovered.tooltip,roles:sourceRoles(e,n)});await pointer(linkMark(e,n),`membership-click:${pair}`);await park();await inspect(`membership-selected:${pair}`,{focus:selected,selected,baseline:before});});
  await task('hover-selection-clear',async()=>{await clear();const before=await inspect('unfocused');const selected={kind:'assertion',id:largest};await pointer(edgeMark(largest),'retain largest');await park();await inspect('persistent largest',{focus:selected,selected,baseline:before});await pointer(nodeMark(highest),'temporary hub hover','hover');await inspect('temporary direct hub roles',{focus:{kind:'node',id:highest},selected,baseline:before});await park();await inspect('restored largest roles',{focus:selected,selected,baseline:before});await clear();await inspect('clear removes all role labels',{baseline:before});});
  for(const size of [{width:1440,height:1000},{width:390,height:844}])await task(`responsive:${size.width}`,async()=>{await page.setViewportSize(size);await page.waitForTimeout(500);await view('overview');await clear();for(const theme of ['light','dark']){await setTheme(theme);const before=await inspect(`responsive:${size.width}:${theme}`,{text:true});check(`no page overflow:${size.width}:${theme}`,!before.overflow);await shot(`responsive-${size.width}-${theme}-top`);await pointer(edgeMark(largest),`responsive-hover:${size.width}:${theme}`,'hover');await inspect(`responsive-roles:${size.width}:${theme}`,{focus:{kind:'assertion',id:largest},baseline:before,text:true});await shot(`responsive-${size.width}-${theme}-roles-hover`);await park();await page.locator('.hypergraph-overview .panel-foot').scrollIntoViewIfNeeded();await shot(`responsive-${size.width}-${theme}-bottom`);}});
 }
}catch(e){report.errors.push({kind:'fatal',message:e.stack});}
finally{
 report.sourceHashAfter=await sha(html);report.sourceUnchanged=report.sha256===report.sourceHashAfter;
 if(report.frozen){report.frozen.hashAfter=await sha(report.frozen.path);report.frozen.unchanged=report.frozen.sha256===report.frozen.hashAfter;}
 report.finishedAt=new Date().toISOString();report.passed=report.sourceUnchanged&&report.frozen?.unchanged!==false&&report.errors.length===0&&report.blockedNetwork.length===0&&report.checks.every(c=>c.ok);
 report.totals={checks:report.checks.length,failed:report.checks.filter(c=>!c.ok).length,states:report.states.length,interactions:report.interactions.length};
 await writeFile(join(output,'diamond-trial-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,...report.totals,sha256:report.sha256,sourceUnchanged:report.sourceUnchanged,frozenUnchanged:report.frozen?.unchanged,errors:report.errors,failures:report.checks.filter(c=>!c.ok)}));await browser.close();if(!report.passed)process.exitCode=1;
}
